version: "3.7"

services:
    product_service:
        build:
            args:
                user: car_rental
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: product_service
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - product_service_mysql
            - product_service_redis

    product_service_mysql:
        image: mysql:5.7.22
        container_name: product_service_db
        restart: always
        environment:
            MYSQL_DATABASE: productdb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3306:3306
        volumes:
            - ./.docker/mysql:/var/lib/mysql

    product_service_nginx:
        image: nginx:1.17-alpine
        container_name: product_service_server
        restart: always
        ports:
            - 8001:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d

    product_service_redis:
        image: redis:alpine
        container_name: product_service_cache
        expose:
            - 6379

networks:
    default:
        external:
            name: rental_service_net

