version: "3.7"

services:
    rental_service:
        build:
            args:
                user: car_rental
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: rental_service
        restart: unless-stopped
        working_dir: /var/www/
        environment:
            PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
            XDEBUG_CONFIG: remote_host=192.168.15.39 #docker network ip.
            PHP_IDE_CONFIG: "serverName=xdebug-docker" #phpstorm variavel de ambiente com o nome do server configurado.
        volumes:
            - ./:/var/www
        expose:
            - 9000
        depends_on:
            - rental_service_mysql
            - rental_service_redis
        networks:
            - rental_service_net

    rental_service_mysql:
        image: mysql:5.7.22
        container_name: rental_service_db
        restart: always
        environment:
            MYSQL_DATABASE: rentaldb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3308:3306
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        networks:
            - rental_service_net

    rental_service_nginx:
        image: nginx:1.17-alpine
        container_name: rental_service_server
        restart: always
        ports:
            - 8003:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - rental_service_net

    rental_service_redis:
        image: redis:alpine
        container_name: rental_service_cache
        expose:
            - 6379
        networks:
            - rental_service_net

networks:
    rental_service_net:
        driver: bridge

