version: "3.7"

services:
    customer_service:
        build:
            args:
                user: car_rental
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: customer_service
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - customer_service_mysql
            - customer_service_redis
        networks:
            - customer_service_net

    customer_service_mysql:
        image: mysql:5.7.22
        container_name: customer_service_db
        restart: always
        environment:
            MYSQL_DATABASE: customerdb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
            MYSQL_USER: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3307:3306
        volumes:
            - ./.docker/mysql:/var/lib/mysql
        networks:
            - customer_service_net

    customer_service_nginx:
        image: nginx:1.17-alpine
        container_name: customer_service_server
        restart: always
        ports:
            - 8002:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx:/etc/nginx/conf.d
        networks:
            - customer_service_net

    customer_service_redis:
        image: redis:alpine
        container_name: customer_service_cache
        expose:
            - 6379
        networks:
            - customer_service_net

networks:
    customer_service_net:
        driver: bridge

